; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = tracker, logger

[env]
monitor_speed = 115200
build_unflags = -std=gnu++11
build_flags = -std=gnu++17

[env:tracker]
platform = teensy
board = teensy40
build_src_filter =
    -<esp32/>
    +<teensy/>
framework = arduino
src_dir = src/teensy

[env:logger]
platform = espressif32
board = esp32dev
build_src_filter =
    +<esp32/>
    -<teensy/>
framework = arduino
src_dir = src/esp32
lib_deps = 
	plerup/EspSoftwareSerial@^8.2.0
