[[inputs.mqtt_consumer]]
servers = ["tcp://127.0.0.1:1883"]
topics = ["rtls/position"]
client_id = "telegraf-rtls"
data_format = "json"
name_override = "position"

[[outputs.influxdb_v2]]
urls = ["http://127.0.0.1:8086/"]
token = "LjWJxyG8tOBJfTcFEbT9pNbvkqwUKbHFpnKaobEXZKVrFTmHj5wHb67EdHWKWBDZDGwHzrtjcrt0e7gQPia3mg=="
organization = "rtls"
bucket = "positions"
